version: "3.9"

services:
    nginx:
        container_name: 'nginx-server'
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443

        restart: always

